t2v_model_path: "/home/rb/Documents/Data/models/top2vec/t2v-bound-1945-1967.model"
t2v_data_path: "/home/rb/Documents/Data/models/top2vec/t2v-bound-1945-1967-data.tsv"
t2v_dist_path_raw: "/home/rb/Documents/Data/models/top2vec/t2v-bound-1945-1967-docdist-raw.tsv"
t2v_keys_path: "/home/rb/Documents/Data/models/top2vec/t2v-bound-1945-1967-keys.tsv"
data_path_speech: "/home/rb/Documents/Data/case-studies/linkage/data-speech-level-full.tsv"
data_path_day: "/home/rb/Documents/Data/case-studies/linkage/data-day-level-full.tsv"
lda_dist_path_speech: "/home/rb/Documents/Data/case-studies/linkage/lda/dists-speech-100"
lda_keys_path_speech: "/home/rb/Documents/Data/case-studies/linkage/lda/keys-speech-100"
lda_dist_path_day: "/home/rb/Documents/Data/case-studies/linkage/lda/dists-day-100"
lda_keys_path_day: "/home/rb/Documents/Data/case-studies/linkage/lda/keys-day-100"
