t2v_model_path_speech: "/home/rb/Documents/Data/case-studies/linkage/top2vec/model-speech-level.model"
t2v_data_path_speech: "/home/rb/Documents/Data/case-studies/linkage/data-speech-level-full.tsv"
t2v_dist_path_speech: "/home/rb/Documents/Data/case-studies/linkage/top2vec/dists-speech-level-reduced.tsv"
t2v_keys_path_speech: "/home/rb/Documents/Data/case-studies/linkage/top2vec/keys-speech-level-reduced.tsv"
data_path_speech: "/home/rb/Documents/Data/case-studies/linkage/data-speech-level-full.tsv"
data_path_day: "/home/rb/Documents/Data/case-studies/linkage/data-day-level-full.tsv"
lda_dist_path_speech: "/home/rb/Documents/Data/case-studies/linkage/lda/dists-speech-100"
lda_keys_path_speech: "/home/rb/Documents/Data/case-studies/linkage/lda/keys-speech-100"
lda_dist_path_day: "/home/rb/Documents/Data/case-studies/linkage/lda/dists-day-100"
lda_keys_path_day: "/home/rb/Documents/Data/case-studies/linkage/lda/keys-day-100"
